/** Odoo xml ids for module menu actions (view_mode / views order). */
export const ODOO_ACTION_XML_ID = {
  crm: {
    leads: 'crm.crm_lead_all_leads',
    pipeline: 'crm.crm_lead_opportunities',
    activities: 'crm.crm_lead_action_my_activities',
    forecast: 'crm.crm_lead_action_forecast',
    stages: 'crm.crm_stage_action',
    lostReasons: 'crm.crm_lost_reason_action',
  },
  sale: {
    orders: 'sale.action_orders',
    quotations: 'sale.action_quotations_with_onboarding',
    toInvoice: 'sale.action_orders_to_invoice',
    toUpsell: 'sale.action_orders_upselling',
    reporting: 'sale.action_order_report_all',
  },
  stock: {
    pickings: 'stock.action_picking_tree_all',
    receipts: 'stock.action_picking_tree_incoming',
    deliveries: 'stock.action_picking_tree_outgoing',
    internal: 'stock.action_picking_tree_internal',
    todo: 'stock.action_picking_tree_ready',
    waiting: 'stock.action_picking_tree_waiting',
    late: 'stock.action_picking_tree_late',
    backorder: 'stock.action_picking_tree_backorder',
    moves: 'stock.stock_move_action',
    orderpoints: 'stock.action_orderpoint',
    overview: 'stock.stock_picking_type_action',
    quants: 'stock.action_view_quants',
    moveLines: 'stock.stock_move_line_action',
    productStock: 'stock.action_product_stock_view',
    warehouse: 'stock.action_warehouse_form',
    locations: 'stock.action_location_form',
    packages: 'stock.action_package_view',
    inventoryAdjustment: 'stock.action_view_inventory_tree',
  },
  account: {
    moves: 'account.action_move_journal_line',
    invoices: 'account.action_move_out_invoice',
    bills: 'account.action_move_in_invoice',
    dashboard: 'account.open_account_journal_dashboard_kanban',
    journalItems: 'account.action_account_moves_all',
    payments: 'account.action_account_payments',
    creditNotes: 'account.action_move_out_refund_type_non_legacy',
    vendorRefunds: 'account.action_move_in_refund_type',
    chartOfAccounts: 'account.action_account_form',
    taxes: 'account.action_tax_form',
    bankStatements: 'account.action_bank_statement_tree',
    reconciliationModels: 'account.action_account_reconcile_model',
    paymentTerms: 'account.action_payment_term_form',
    fiscalPositions: 'account.action_account_fiscal_position_form',
  },
  event: {
    events: 'event.action_event_view',
    registrations: 'event.action_registration',
    registrationDesk: 'event.event_barcode_action_main_view',
  },
  calendar: {
    events: 'calendar.action_calendar_event',
  },
  product: {
    products: 'product.product_template_action_all',
  },
  project: {
    projects: 'project.open_view_project_all',
    tasks: 'project.action_view_all_task',
    stages: 'project.project_project_stage_action',
    taskStages: 'project.open_task_type_form',
    milestones: 'project.action_view_project_milestone',
  },
  mrp: {
    productions: 'mrp.mrp_production_action',
  },
  attendance: {
    kiosk: 'hr_attendance.hr_attendance_action_kiosk_mode',
  },
  expense: {
    my: 'hr_expense.action_hr_expense_my_expenses_all',
  },
  recruitment: {
    applicants: 'hr_recruitment.action_hr_job_applications',
    stages: 'hr_recruitment.action_hr_recruitment_stage',
  },
} as const
